import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  BookOpen, 
  Sparkles, 
  FileText, 
  MessageSquare, 
  TrendingUp, 
  Bot, 
  CheckSquare, 
  ArrowRight,
  X
} from 'lucide-react';

interface ResourceItem {
  id: string;
  title: string;
  description: string;
  category: string;
  icon: string;
  readTime: string;
  bgGradient: string;
  details: string;
}

export const ResourcesSection: React.FC = () => {
  const [selectedResource, setSelectedResource] = useState<ResourceItem | null>(null);

  const resources: ResourceItem[] = [
    {
      id: 'res-1',
      title: 'Resume Formatting Tips for 2026 ATS',
      description: 'Learn how to pass automated ATS filters by using correct font density, standard section titles, and quantifiable impact metrics.',
      category: 'Resume Guide',
      icon: 'FileText',
      readTime: '5 min read',
      bgGradient: 'from-blue-600 to-indigo-700',
      details: '1. Use standard font families like Inter or Arial.\n2. Keep experience section bullets in Action Verb + Task + Quantified Impact format.\n3. Avoid putting crucial contact details inside headers/footers where legacy ATS parsers fail.'
    },
    {
      id: 'res-2',
      title: 'Top 50 Technical Interview Questions',
      description: 'Handpicked interview questions asked in Google, Amazon, and Swiggy for SDE-1 and Frontend Developer roles.',
      category: 'Interview Prep',
      icon: 'MessageSquare',
      readTime: '12 min read',
      bgGradient: 'from-purple-600 to-indigo-800',
      details: 'Covers JavaScript event loop, closures, React fiber architecture, SQL indexing, system design basics, and behavioral STAR method responses.'
    },
    {
      id: 'res-3',
      title: 'Software & Data Salary Guide 2026',
      description: 'Benchmark expected compensation packages across Tier-1, Tier-2 cities in India for freshers and experienced developers.',
      category: 'Salary Insights',
      icon: 'TrendingUp',
      readTime: '8 min read',
      bgGradient: 'from-emerald-600 to-teal-800',
      details: 'Data compiled from 15,000+ candidate offers across Bangalore, Mumbai, Delhi NCR, and Hyderabad for React, Python, Java, and Data Science roles.'
    },
    {
      id: 'res-4',
      title: 'AI Career Assistant & Mentor',
      description: 'Get tailored career advice, salary negotiation scripts, and skill gap analysis generated by AI.',
      category: 'AI Mentor',
      icon: 'Bot',
      readTime: 'Interactive',
      bgGradient: 'from-amber-600 to-orange-700',
      details: 'Use our AI mentor to generate custom cover letters, practice mock technical questions, or evaluate your current resume score.'
    },
    {
      id: 'res-5',
      title: 'Government Exam Syllabus Breakdown',
      description: 'Detailed section-wise syllabus and preparation strategies for SSC CGL, UPSC, Railways RRB, and Banking IBPS PO.',
      category: 'Govt Prep',
      icon: 'BookOpen',
      readTime: '10 min read',
      bgGradient: 'from-slate-800 to-slate-950',
      details: 'Includes download link for official PDFs, previous year cut-offs, and free daily mock test series.'
    },
    {
      id: 'res-6',
      title: 'Fresher Campus Placement Playbook',
      description: 'Complete guide for 2025/2026 batch students to crack off-campus hiring drives and secure high-paying PPOs.',
      category: 'Campus Guide',
      icon: 'CheckSquare',
      readTime: '7 min read',
      bgGradient: 'from-blue-700 to-cyan-800',
      details: 'Covers GitHub portfolio showcase, cold emailing recruiters on LinkedIn, aptitude test speed tricks, and HR negotiation techniques.'
    }
  ];

  return (
    <section className="py-20 bg-white" id="resources">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-14">
          <div className="inline-flex items-center gap-1.5 px-3.5 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold uppercase tracking-widest font-display mb-3 border border-blue-200">
            <BookOpen className="w-3.5 h-3.5" /> Career Knowledge Hub
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight font-display">
            Career Resources & Interview Guides
          </h2>
          <p className="text-slate-600 text-sm mt-2">
            Free playbooks, salary benchmarks, and interview preparation guides updated for 2026 hiring standards.
          </p>
        </div>

        {/* Resources Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {resources.map((res) => (
            <motion.div
              key={res.id}
              whileHover={{ y: -5 }}
              transition={{ duration: 0.2 }}
              onClick={() => setSelectedResource(res)}
              className="bg-slate-50 rounded-3xl p-6 border border-slate-200/90 hover:border-blue-300 shadow-2xs hover:shadow-xl transition-all flex flex-col justify-between group cursor-pointer"
            >
              <div>
                <div className="flex items-center justify-between mb-4">
                  <span className="text-[11px] font-bold bg-blue-100 text-blue-800 px-3 py-1 rounded-full">
                    {res.category}
                  </span>
                  <span className="text-[11px] font-semibold text-slate-400">{res.readTime}</span>
                </div>

                <h3 className="font-extrabold text-lg text-slate-900 group-hover:text-blue-600 transition-colors leading-snug mb-2">
                  {res.title}
                </h3>

                <p className="text-xs text-slate-600 leading-relaxed line-clamp-3">
                  {res.description}
                </p>
              </div>

              <div className="pt-4 mt-6 border-t border-slate-200/80 flex items-center justify-between">
                <span className="text-xs font-bold text-blue-600 group-hover:translate-x-1 transition-transform inline-flex items-center gap-1">
                  Read Full Resource <ArrowRight className="w-4 h-4" />
                </span>
                <span className="text-[10px] text-slate-400 uppercase font-semibold">Free Access</span>
              </div>
            </motion.div>
          ))}
        </div>

      </div>

      {/* Resource Detail Modal */}
      <AnimatePresence>
        {selectedResource && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl p-6 sm:p-8 max-w-lg w-full relative shadow-2xl border border-slate-200"
            >
              <button
                onClick={() => setSelectedResource(null)}
                className="absolute top-6 right-6 p-2 rounded-full text-slate-400 hover:text-slate-800"
              >
                <X className="w-5 h-5" />
              </button>

              <span className="text-xs font-bold bg-blue-100 text-blue-800 px-3 py-1 rounded-full inline-block mb-3">
                {selectedResource.category}
              </span>

              <h3 className="font-extrabold text-xl text-slate-900 mb-3">{selectedResource.title}</h3>
              <p className="text-xs text-slate-600 mb-4">{selectedResource.description}</p>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 text-xs text-slate-800 whitespace-pre-line leading-relaxed mb-6 font-medium">
                {selectedResource.details}
              </div>

              <button
                onClick={() => setSelectedResource(null)}
                className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs rounded-xl shadow-xs"
              >
                Got It
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </section>
  );
};
